name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff pytest pytest-cov
      
      - name: Lint
        run: ruff check . --exclude scripts/
      
      - name: Run type checking
        run: |
          mypy generate_llm_yaml
      
      - name: Run tests
        run: |
          pytest --cov=generate_llm_yaml tests/ 